version: '3.8'

services:
  c1:
    build: ./c1
    platform: linux/amd64
    container_name: C1
    tty: true
    networks:
      - lab5_net

  c2:
    build: ./c2
    platform: linux/amd64
    container_name: C2
    tty: true
    networks:
      - lab5_net

  c3:
    build: ./c3
    platform: linux/amd64
    container_name: C3
    tty: true
    networks:
      - lab5_net

  s1:
    # Cambia "./s1" por "./c4" o "./C4_S1" dependiendo de cómo llamaste a tu carpeta
    build: ./s1 
    platform: linux/amd64
    container_name: S1
    tty: true
    ports:
      - "2222:22" # Mapea el puerto 22 del contenedor al 2222 de tu host local
    networks:
      - lab5_net

networks:
  lab5_net:
    driver: bridge